// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyqaoxdFcCIcBoLpspzjZrZSFITgBu48c',
    appId: '1:524775540771:web:09b2036e0f2694c7e2c996',
    messagingSenderId: '524775540771',
    projectId: 'disaster-management-app-606f8',
    authDomain: 'disaster-management-app-606f8.firebaseapp.com',
    storageBucket: 'disaster-management-app-606f8.appspot.com',
    measurementId: 'G-7ZRCHSLC2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkTMLdb8s_WXPdnEEknXaekjeac4XAniw',
    appId: '1:524775540771:android:31b585d16029166ae2c996',
    messagingSenderId: '524775540771',
    projectId: 'disaster-management-app-606f8',
    storageBucket: 'disaster-management-app-606f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtrUqINDe9XmXtSjDb0z4hZeKgEBiCBXI',
    appId: '1:524775540771:ios:3c3853b25b7f921ee2c996',
    messagingSenderId: '524775540771',
    projectId: 'disaster-management-app-606f8',
    storageBucket: 'disaster-management-app-606f8.appspot.com',
    iosBundleId: 'com.example.disasterAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtrUqINDe9XmXtSjDb0z4hZeKgEBiCBXI',
    appId: '1:524775540771:ios:3c3853b25b7f921ee2c996',
    messagingSenderId: '524775540771',
    projectId: 'disaster-management-app-606f8',
    storageBucket: 'disaster-management-app-606f8.appspot.com',
    iosBundleId: 'com.example.disasterAid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyqaoxdFcCIcBoLpspzjZrZSFITgBu48c',
    appId: '1:524775540771:web:4a287f85b4e76541e2c996',
    messagingSenderId: '524775540771',
    projectId: 'disaster-management-app-606f8',
    authDomain: 'disaster-management-app-606f8.firebaseapp.com',
    storageBucket: 'disaster-management-app-606f8.appspot.com',
    measurementId: 'G-EZNEX1XZEQ',
  );

}